[package]
name = "penumbra-wallet-next"
version = "0.1.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The wallet RPC library for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto" }
penumbra-chain = { path = "../chain" }
penumbra-crypto = { path = "../crypto" }
penumbra-stake = { path = "../stake" }
penumbra-transaction = { path = "../transaction" }

sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "offline", "sqlite" ] }
tokio = { version = "1.16", features = ["full"]}
anyhow = "1"
directories = "4.0.1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
structopt = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2"